# Generated by Django 4.2.29 on 2026-03-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPlanilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/%Y/%m/%d/')),
                ('data_referencia', models.DateField(default=django.utils.timezone.localdate)),
                ('inseridos', models.PositiveIntegerField(default=0)),
                ('atualizados', models.PositiveIntegerField(default=0)),
                ('preservados', models.PositiveIntegerField(default=0)),
                ('ignorados', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=180)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('status_origem', models.CharField(blank=True, max_length=80)),
                ('guiche_origem', models.CharField(blank=True, max_length=80)),
                ('observacao', models.TextField(blank=True)),
                ('resultado', models.CharField(choices=[('inserido', 'Inserido'), ('atualizado', 'Atualizado'), ('preservado', 'Preservado'), ('ignorado', 'Ignorado')], max_length=20)),
                ('detalhe', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('importacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='importacao.importacaoplanilha')),
            ],
            options={
                'ordering': ['linha'],
            },
        ),
    ]
