# Generated by Django 4.2.29 on 2026-03-21 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('importacao', '0001_initial'),
        ('tenants', '0001_initial'),
        ('guiches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('nome_normalizado', models.CharField(editable=False, max_length=180)),
                ('data_referencia', models.DateField(default=django.utils.timezone.localdate)),
                ('hora_agendada', models.TimeField(blank=True, null=True)),
                ('hora_chegada', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('chamado', 'Chamado'), ('atendido', 'Atendido'), ('ausente', 'Ausente')], default='aguardando', max_length=20)),
                ('classificacao_fila', models.CharField(choices=[('no_horario', 'No horário'), ('atrasado', 'Atrasado'), ('encaixe', 'Encaixe')], default='no_horario', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('import_key', models.CharField(editable=False, max_length=255)),
                ('chamado_em', models.DateTimeField(blank=True, null=True)),
                ('atendido_em', models.DateTimeField(blank=True, null=True)),
                ('ausente_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('guiche', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='guiches.guiche')),
                ('origem_importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='importacao.importacaoplanilha')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='tenants.tenant')),
            ],
            options={
                'ordering': ['hora_agendada', 'hora_chegada', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='atendimento.atendimento')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos_atendimento', to='tenants.tenant')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='atendimento',
            constraint=models.UniqueConstraint(fields=('tenant', 'import_key'), name='uniq_atendimento_import_key_por_tenant'),
        ),
    ]
