# Generated by Django 4.2.29 on 2026-03-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='documento',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='telefone',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tipo_servico',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='classificacao_fila',
            field=models.CharField(choices=[('no_horario', 'No horario'), ('atrasado', 'Atrasado'), ('encaixe', 'Encaixe')], default='no_horario', max_length=20),
        ),
    ]
