# Generated by Django 4.2.29 on 2026-03-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guiche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=30)),
                ('ativo', models.BooleanField(default=True)),
                ('situacao', models.CharField(choices=[('livre', 'Livre'), ('chamando', 'Chamando'), ('em_atendimento', 'Em atendimento'), ('inativo', 'Inativo')], default='livre', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guiches', to='tenants.tenant')),
            ],
            options={
                'ordering': ['codigo', 'nome'],
                'unique_together': {('tenant', 'codigo')},
            },
        ),
    ]
